# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022
#
# You may uncomment the following lines if you want "ls" to be colorized:
export LS_OPTIONS='--color=auto'
#eval "dircolors"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

export LANG=fr_BE.UTF-8
export LANGUAGE=fr_BE.UTF-8
export LC_COLLATE=C
export LC_CTYPE=fr_BE.UTF-8